language: java
sudo: false
install: true
cache:
  directories:
  - "$HOME/.gradle/caches/2.14.1"
  - "$HOME/.gradle/caches/jars-1"
  - "$HOME/.gradle/caches/jars-2"
  - "$HOME/.gradle/caches/jars-3"
  - "$HOME/.gradle/native"
  - "$HOME/.gradle/daemon"
  - "$HOME/.gradle/wrapper"
  - "$HOME/.gradle/minecraft"
jdk:
  - oraclejdk8  
jobs:
 include:
 -stage: sonar
  addons:
   sonarcloud:
    organization: "bartimaeusnek-github"
    token:
     secure: "KW2U8HenTpLQOXT+OxCsu4noCKH6ZkUATld36YTbwAwzVKt6aesqtKHkZuo+Y+a143GI184pdnhMcRB1F49Wf0IQTkOhvopfnSEg+AKWZJb+gAbZQaYkaoe04pVzdwnpBXPDZR0DnTJX09VJGlES0RMiYfaQDHAYuPRQRBf17mLWvhXf7ZfNshGLikmzQcXWoXMpB+z9BaJ9Vr9/+Jn4Geuh9MWsbc2xZyQU8hoTTtKxqj5sTVRkwmxTf0ooGrMKohoOQ5JeZLDWM0Z/7KW64kFCE3xDrKg2gnKyKNLU6qIwbgCtVkcqGb28tXuqNdRSZ5BHb70dZb0E2+9VGhS7xPA8iUVmktJRKKG+f34HtDlsXqA00SEF2u+fq+TDz7fcPHLM8z1IcUI2XF5c5A/6E1k161i3kMB9xpd5Rq4waywo+/2j+L2CE6u5aj7BeL7KUQKD7k5gx3bXUyIo2QdjzeJeUJTSaxchcae9iIO+W6rwc68fD5/UNHVp+O75QNz2B+pklz6hCFVaoUep8rl4LO58ODBU1GL4JfeTM0RzOofOFepPXIi39iCk89c61WBtxX8RPkv3nBDsrXCGU7UNH1thP1nmgCfB4HGRxixWBAnmPDHNLEW81RG+meGRpHX7RkWISmrl95x15QXb016hldvK3sAegxxVPUdyJxRplgE="
  script: "./gradlew sonarqube"
 -stage: buildAndDeploy
  script: "./gradlew build"
  deploy:
   provider: releases
   api_key:
    secure: "fZcmkACyjZv8rEjG9hjsNq6ZT/przBeSGYzdfpT55YV/xWXj18Lkqr4XfrY4GiTp/pJwOGYT5dUUybRSlMM3eSMWNcAjBOW7WuJDEkZIHPKTb5/H+SJgUeuxj0W7cTqANWvYlMaNv2WSQfV2UW09xvSuMJuVMUcng1E1AZj6hF5285DrbxygEiF0ZY77Rsq+Q3l29bJxrj+x5D8ui8m2rn2tug8+W5/iCxYLpNEQ0hLcxPOh/0GbdHtsett81F9CVW+aPnVE7AlVnGK6lftWfiwPHqglpbx7lwEr6/gHBFuJIasreP5+GJvMx0D96la4KRvREFfS4eAZXLG7Syx0zzVInf6SHtMtzVM7heIY/aEnZ8clYxfnOBw10hyuev4QUdCvBb0tndsrCBI4kEIqvvNVcpHatJyzr+q0gj7mvGsXu3DIN5teo6h6DBJrbuhS6QKM2Lm/FsrboeSfIFlXE94IORmQzH0evgbk8u+CER1VNvrRHBngfEqypGd06TbXVW/uvfCedpvOZ3ewuPhLqOZHCzXbjBDAf0xzIcwWIzkEcpT4hXujHexyGAPJVHZDO2KA/7oFWEks9gCdnSJ7Qet5VwsUyDHzsDACix5+9tiYc0CFyRcEuWsvfVCqYCs1NwDJcHH0KxFceah1UzvS+6QB5MFfR5uFxhgUA4qsMd0="
   file: build/libs/*.jar
   skip_cleanup: true
   file_glob: true
   on:
    repo: bartimausnek/bartworks
    tags: false