version: 2
jobs:
  build:
    working_directory: ~/repo
    
    docker:
      - image: circleci/openjdk:8-jdk
      
      
    environment:
      JVM_OPTS: -Xmx3200m
      
      
    steps:
      - checkout
      
      - run:
          name: Run build
          command:  export TERM=${TERM:-dumb} 
          # && ./gradlew clean build
      
      - run: sudo chmod +x gradlew
      
      #https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-src.zip
      
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}
          
      - run:
          name: Download Build Script
          command: wget https://alkcorp.overminddl1.com/GTPP_BuildScript.sh
          
      - run:
          name: Run Build Script
          command: sh GTPP_BuildScript.sh ${CIRCLE_BUILD_NUM} "${CIRCLE_BRANCH}" "${CIRCLE_USERNAME}" "${CIRCLE_SHA1}" "${CIRCLE_PROJECT_REPONAME}" "${CIRCLE_PROJECT_USERNAME}" "https://github.com/draknyte1/GTplusplus/archive/master.zip"
          
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}

      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: build/libs
          #destination: builds
      #- store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          #path: build/libs
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
