
name: Build and test

on:
  pull_request:
    branches: [ master, main, release/** ]
  push:
    branches: [ master, main, release/** ]

jobs:
  optimize-images:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/optimize-images.yml@master
    secrets: inherit
    
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@master
    secrets: inherit
    with:
     timeout: 150
