name: Forbidden isModLoaded

on:
  pull_request:
    branches: [ master, main, release/** ]
  push:
    branches: [ master, main, release/** ]

jobs:
  test-forbidden-ismodloaded:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect forbidden isModLoaded calls
        shell: bash
        run: |
          ! grep -E -r '(BartWorks|GalactiGreg|GGFab|GoodGenerator|GTNHIntergalactic|GTNHLanthanides|GregTech|GTPlusPlus|KekzTech|KubaTech|TecTech|NEIOrePlugin)\.isModLoaded' src/main/java || exit 1
          ! grep -E -r 'isModLoaded\(".*")' src/main/java || exit 1
          ! grep -E -r '@(Optional.|)Method\(modid = ".*")' src/main/java || exit 1
          ! grep -E -r '@(Optional.|)Interface\(.*modid = ".*".*)' src/main/java || exit 1
