name: Forbidden getModItems

on:
  pull_request:
    branches: [ master, main, release/** ]
  push:
    branches: [ master, main, release/** ]

jobs:
  test-forbidden-getmoditems:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect forbidden getModItem calls
        shell: bash
        run: |
          ! grep -E -r 'getModItem\(.*(BartWorks|GalactiGreg|GGFab|GoodGenerator|GregTech|GTNHIntergalactic|GTNHLanthanides|GTPlusPlus|KekzTech|KubaTech|TecTech|NEIOrePlugin)\.ID' src/main/java || exit 1
          ! grep -E -r 'getModItem\(".*", .*)' src/main/java || exit 1
